/*
 * This source file was generated by the Gradle 'init' task
 */
package inventario;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner lector = new Scanner(System.in);

        // 1. Pedir el nombre
        System.out.print("Por favor, ingresa tu nombre: ");
        String nombre = lector.nextLine();

        // 2. Pedir el año de nacimiento
        System.out.print("Ingresa tu año de nacimiento: ");
        int anioNacimiento = lector.nextInt();

        // 3. Calcular la edad
        int edad = 2026 - anioNacimiento;

        // 4. Mostrar el resultado final
        System.out.println("Hola " + nombre + ". Tienes " + edad + " años. Esto es una prueba");

        lector.close();
    }
}