/*
 * This source file was generated by the Gradle 'init' task
 */
package inventario;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner lector = new Scanner(System.in);

        // 1. Pedir el nombre
        System.out.print("Por favor, ingresa tu nombre: ");
        String nombre = lector.nextLine();

        int edad = -1; // Iniciamos con un valor fuera de rango para que entre al bucle

        // 2. Bucle para pedir y validar la edad
        while (edad < 0 || edad > 100) {
            System.out.print("Ingresa tu año de nacimiento: ");
            int anioNacimiento = lector.nextInt();
            
            // Calculamos la edad
            edad = 2026 - anioNacimiento;

            // Verificación del rango
            if (edad < 0 || edad > 100) {
                System.out.println("Edad fuera de rango. Intenta de nuevo.");
            }
        }

        // 3. Mostrar el resultado final solo cuando la edad sea válida
        System.out.println("Hola " + nombre + ". Tienes " + edad + " años. Esto es una prueba");

        lector.close();
    }
}